In [241]:
import pandas as pd

In [242]:
df=pd.read_csv('Visit.csv')

In [243]:
print(df.columns)

Index(['Unnamed: 0', 'Zone', 'State', 'City', 'Name', 'Type',
       'Establishment Year', 'time needed to visit in hrs',
       'Google review rating', 'Entrance Fee in INR',
       'Airport with 50km Radius', 'Weekly Off', 'Significance',
       'DSLR Allowed', 'Number of google review in lakhs',
       'Best Time to visit'],
      dtype='object')

In [244]:
col=['Type','Google review rating','Number of google review in lakhs','Entrance Fee in INR']

In [245]:
print(col)

['Type', 'Google review rating', 'Number of google review in lakhs', 'Entrance Fee in INR']

In [246]:
df=df[col]
df

,Type,Google review rating,Number of google review in lakhs,Entrance Fee in INR
0,War Memorial,4.6,2.60,0
1,Tomb,4.5,0.40,30
2,Temple,4.6,0.40,60
3,Theme Park,4.1,0.27,50
4,Observatory,4.2,0.31,15
...,...,...,...,...
320,Temple,4.6,0.18,0
321,Fort,4.5,1.30,40
322,Museum,4.7,0.15,10
323,Palace,4.4,0.51,200
324,Museum,4.5,0.63,200

In [247]:
df.shape

(325, 4)

In [248]:
print(df.isna().sum())

Type                                0
Google review rating                0
Number of google review in lakhs    0
Entrance Fee in INR                 0
dtype: int64

In [249]:
df=df.loc[df['Entrance Fee in INR']!=0]

In [250]:
print(df.to_string())

                   Type  Google review rating  Number of google review in lakhs  Entrance Fee in INR
1                  Tomb                   4.5                            0.4000                   30
2                Temple                   4.6                            0.4000                   60
3            Theme Park                   4.1                            0.2700                   50
4           Observatory                   4.2                            0.3100                   15
7                  Fort                   4.5                            1.5000                   35
10                 Park                   4.1                            0.2300                   35
12               Museum                   4.5                            0.0800                   20
13                  Zoo                   4.1                            0.4100                   80
14             Monument                   4.5                            1.3700                   35
15              Science                   4.4                            0.2300                   70
18               Museum                   4.6                            0.3400                  500
19        National Park                   4.3                            0.6000                   50
24       Amusement Park                   4.3                            0.2700                 1149
25             Monument                   4.3                            0.3500                  550
26       Amusement Park                   1.4                            0.9500                 1149
27               Palace                   4.2                            0.9000                  500
28     Botanical Garden                   4.4                            1.5000                   20
32             Landmark                   4.5                            2.1000                   25
33                 Fort                   4.4                            1.2000                   30
35          Film Studio                   4.4                            0.4500                 1150
36               Museum                   4.4                            0.6700                   20
37                Tombs                   4.4                            0.2000                   25
39               Palace                   4.4                            0.4500                   80
40                  Zoo                   4.2                            0.8600                   50
41                 Park                   4.1                            0.7300                   20
42               Museum                   4.6                            0.7300                   30
44               Museum                   4.6                            0.1800                   50
47       Cricket Ground                   4.1                            0.1000                 2500
48                  Zoo                   4.3                            0.6600                   25
49              Science                   4.4                            0.8800                   60
55            Waterfall                   4.6                            0.3000                  500
65       Bird Sanctuary                   3.9                            0.0300                   10
68        National Park                   4.5                            0.0800                 3500
70               Palace                   4.4                            0.1700                  200
72             Cultural                   4.9                            0.1000                 7500
73             Monument                   4.6                            0.6700                  350
77                 Lake                   4.5                            0.3000                   10
78              Science                   4.4                            0.1100                  500
79               Palace                   4.4                            1.3000                   50
80               Palace                   4.4                            0.5100                  300
81                 Fort                   4.4                            0.5600                   50
82   Wildlife Sanctuary                   4.6                            0.0900                  500
85                 Fort                   4.6                            0.6400                  100
86                 Fort                   4.6                            1.9000                   40
88                 Fort                   4.5                            0.3200                   50
89                 Fort                   4.6                            1.5000                  100
90                 Fort                   4.5                            0.3000                   35
95     Sculpture Garden                   4.5                            0.5000                   30
101  Wildlife Sanctuary                   4.5                            2.2000                  300
102       National Park                   4.3                            0.1400                   50
103      Bird Sanctuary                   3.8                            0.1000                   50
105                Fort                   4.5                            0.2200                   20
107                Fort                   4.4                            0.1100                   20
109            Cultural                   4.4                            0.1000                  100
110      Amusement Park                   4.6                            0.4100                  750
111              Palace                   4.6                            2.5000                   50
116                Cave                   4.6                            0.2000                   30
117           Waterfall                   4.6                            0.2300                   30
120           Mausoleum                   4.5                            0.2500                   20
121       National Park                   4.4                            0.1500                  300
122              Temple                   4.7                            0.1100                   15
123                Fort                   4.4                            1.2000                   50
124                Cave                   4.6                            0.2100                   30
125            Vineyard                   4.1                            0.1000                  300
131                Cave                   4.4                            0.2700                   25
133              Valley                   4.4                            0.0500                  300
135                Cave                   4.7                            0.4900                   30
136             Temples                   4.7                            0.0900                   40
137            Monument                   4.7                            0.0100                   30
138              Palace                   4.4                            0.6300                   10
139                Fort                   4.5                            0.4000                   75
142           Waterfall                   4.6                            0.0650                   15
143  Wildlife Sanctuary                   4.5                            0.1000                  100
144       National Park                   4.5                            0.0500                   50
145                Fort                   4.8                            0.1000                   10
146                Site                   3.9                            0.0300                   50
147    Prehistoric Site                   4.6                            0.0700                   25
155       National Park                   4.5                            0.2000                   50
158                Fort                   4.4                            0.1000                  150
161     Adventure Sport                   4.8                            0.0100                 2500
167          Ski Resort                   3.8                            0.1000                 1500
171                Cave                   4.5                            0.0100                   25
172           Waterfall                   4.2                            0.5500                   15
175  Wildlife Sanctuary                   4.3                            0.0100                  150
176             Orchard                   4.0                            0.0250                   50
177       National Park                   4.4                            0.3000                  100
180       National Park                   4.7                            0.0350                  150
181           Mausoleum                   4.6                            2.2500                   50
183            Monument                   4.4                            0.4500                   50
188                Fort                   4.4                            0.2500                   15
189            Monument                   4.6                            0.0650                    5
190            Monument                   4.4                            0.0700                   40
191      Bird Sanctuary                   4.3                            0.0350                   30
192                Fort                   4.1                            0.0165                   20
194                 Zoo                   4.2                            0.2100                  150
196                Lake                   4.9                            0.1500                   20
197              Valley                   4.6                            0.1100                  100
201           Monastery                   4.7                            0.0500                   20
204           Monastery                   4.7                            0.0150                   20
205       National Park                   4.3                            0.0100                  100
206       National Park                   4.4                            0.0200                   20
210           Monastery                   4.7                            0.0500                   30
216  Wildlife Sanctuary                   4.4                            0.0350                  250
217       National Park                   4.4                            0.0650                   60
219              Palace                   4.5                            0.1800                   10
222       National Park                   4.4                            0.0700                  100
223              Palace                   4.5                            0.0900                   20
226              Temple                   4.7                            0.8300                   40
239            Memorial                   4.6                            0.4700                   20
240                Lake                   4.1                            0.6100                   10
244              Temple                   4.6                            0.0900                   40
253                Cave                   4.4                            0.1100                   65
255      Bird Sanctuary                   4.4                            0.7000                   10
260              Museum                   4.6                            0.4900                   40
261                Cave                   4.5                            0.3100                   60
263                 Zoo                   4.1                            0.2500                   20
264            Aquarium                   3.8                            0.0300                   20
265              Museum                   4.3                            0.0650                   10
266                Hill                   4.3                            0.1500                   20
267           Monastery                   4.6                            0.0150                   20
268   Religious Complex                   4.7                            0.1200                   50
269           Monastery                   4.6                            0.0350                   10
270                Park                   4.8                            0.1000                   50
274       National Park                   4.5                            0.0680                  650
278       National Park                   4.6                            0.1900                  500
280  Wildlife Sanctuary                   4.4                            0.0370                  500
282              Palace                   4.5                            0.0350                   10
284       Rock Carvings                   4.5                            0.0250                   20
289               Beach                   4.5                            0.0150                  200
290            Landmark                   4.7                            0.1200                   30
293     Natural Feature                   4.4                            0.0150                  250
299                 Zoo                   4.3                            0.5000                   30
301                Park                   4.4                            0.3100                   10
302       Entertainment                   4.4                            0.3000                 1100
309      Amusement Park                   4.5                            0.9500                  890
310                 Zoo                   4.4                            0.8100                   50
315          Race Track                   4.6                            7.4000                 1500
318              Museum                   4.4                            0.2400                   50
321                Fort                   4.5                            1.3000                   40
322              Museum                   4.7                            0.1500                   10
323              Palace                   4.4                            0.5100                  200
324              Museum                   4.5                            0.6300                  200

In [251]:
df=pd.get_dummies(df,dtype=int)
df

,Google review rating,Number of google review in lakhs,Entrance Fee in INR,Type_Adventure Sport,Type_Amusement Park,Type_Aquarium,Type_Beach,Type_Bird Sanctuary,Type_Botanical Garden,Type_Cave,...,Type_Temple,Type_Temples,Type_Theme Park,Type_Tomb,Type_Tombs,Type_Valley,Type_Vineyard,Type_Waterfall,Type_Wildlife Sanctuary,Type_Zoo
1,4.5,0.40,30,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,4.6,0.40,60,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,4.1,0.27,50,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,4.2,0.31,15,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,4.5,1.50,35,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,4.4,0.24,50,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
321,4.5,1.30,40,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
322,4.7,0.15,10,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
323,4.4,0.51,200,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
324,4.5,0.63,200,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [252]:
print((df['Entrance Fee in INR']!=0).sum())

142

In [253]:
print(df.shape)

(142, 47)

In [254]:
x=df.drop(columns=['Entrance Fee in INR'])
y=df['Entrance Fee in INR']

In [255]:
x

,Google review rating,Number of google review in lakhs,Type_Adventure Sport,Type_Amusement Park,Type_Aquarium,Type_Beach,Type_Bird Sanctuary,Type_Botanical Garden,Type_Cave,Type_Cricket Ground,...,Type_Temple,Type_Temples,Type_Theme Park,Type_Tomb,Type_Tombs,Type_Valley,Type_Vineyard,Type_Waterfall,Type_Wildlife Sanctuary,Type_Zoo
1,4.5,0.40,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,4.6,0.40,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,4.1,0.27,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,4.2,0.31,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,4.5,1.50,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,4.4,0.24,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
321,4.5,1.30,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
322,4.7,0.15,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
323,4.4,0.51,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
324,4.5,0.63,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [256]:
y

1       30
2       60
3       50
4       15
7       35
      ...
318     50
321     40
322     10
323    200
324    200
Name: Entrance Fee in INR, Length: 142, dtype: int64

In [257]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [258]:
model=LinearRegression()

In [259]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.12)
model.fit(x_train,y_train)

LinearRegression()

In [260]:
model.score(x_train,y_train)

0.8588384204508885

In [261]:
model.score(x_test,y_test)

-2.4452044531549846e+24

In [262]:
from sklearn.linear_model import Lasso
model2=Lasso(alpha=25,max_iter=100,tol=0.1)
model2.fit(x_train,y_train)

Lasso(alpha=25, max_iter=100, tol=0.1)

In [263]:
model2.score(x_train,y_train)

0.513081726194353

In [264]:
model2.score(x_test,y_test)

-14.71360158925399

In [265]:
from sklearn.linear_model import Ridge
model3=Ridge(alpha=25,max_iter=100,tol=0.1)
model3.fit(x_train,y_train)
model3.score(x_train,y_train)

0.08410021373294829

In [240]:
model3.score(x_test,y_test)

-1.818022992269586